name: Cypress Tests

on:
  # Run tests on Pull Requests
  pull_request:
    branches:
      - main
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      testType:
        description: "Which tests to run (positive, negative, all)"
        required: false
        default: "all"
  # Run all tests on any merge to main
  push:
    branches:
      - main

jobs:
  positive_cases:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.testType == 'all' || github.event_name == 'push' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run All Cypress Tests
      env:
        CI: true
      run: npm run cypress:run:negative
  negative_cases:
      runs-on: ubuntu-latest
      if: ${{ github.event.inputs.testType == 'all' || github.event_name == 'push' }}
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
  
      - name: Install dependencies
        run: npm install
  
      - name: Run All Cypress Tests
        env:
          CI: true
        run: npm run cypress:run:negative
